
## instructions at http://about.travis-ci.org/docs/user/languages/python/

## settings
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  
before_install:
    - pip install sphinx


# command to run tests
script:
    - cd docs
    - make html
    


