
## instructions at http://about.travis-ci.org/docs/user/languages/python/

## settings
language: python
python:
python:
  - 2.6
  - 2.7
  
before_install:
    - pip install sphinx


# command to run tests
script:
    - cd docs
    - make html
    


